language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - python-dev
    - python-numpy

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./test/xdata_array_test