language: cpp

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    #- ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.6
    packages:
    - swig
    - python3-dev
    - python3-numpy
    - libgtest-dev

compiler:
  - clang
  - gcc
  
before_script:
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script:
  - mkdir build && cd build
  - sh ../.travis_build.sh
  - travis_debug
